console.log('n1');
const { pipeline, env } = await import('@xenova/transformers');
console.log('n2 imported');
env.allowLocalModels = false;
env.cacheDir = process.env.TRANSFORMERS_CACHE;
env.backends.onnx.wasm.numThreads = 1;
const t = Date.now();
const p = await pipeline('feature-extraction', 'Xenova/multilingual-e5-small', { quantized: true });
console.log('pipeline ms', Date.now()-t);
const t2 = Date.now();
const o = await p(['query: test'], { pooling:'mean', normalize:true });
console.log('first infer ms', Date.now()-t2, o.dims);
